### ISSUE TITLE
Encode UTF8 chars in document names

### ISSUE THREAD

**Issue by raucao** [skddc/rs-backup#11]
Currently, it does the wrong requests with unencoded characters.

**Comment by gregkare** [comment]
Right now the "é" (e with acute accent) is sent by rs-backup as `\xE9` as part of a URL. The RS.js library encodes that as `\xC3\xA9` when performing the PUT request, which is valid hex encoded UTF-8 (https://unicode-table.com/en/00E9/)

Typing `"\xE9"` in a node REPL results in the e with acute accent character, but that doesn't appear to be a valid encoded version of the `U+00E9` unicode character

**Comment by gregkare** [comment]
Request from rs-backup: `/gk-test-2018-04-12/myfavoritedrinks/bois-band\xE9`
Request from myfavoritedrinks: `/gk-test-2018-04-12/myfavoritedrinks/bois-band\xC3\xA9`

**Comment by gregkare** [comment]
And there's a site using the utf8 npm module to encode/decode utf8: https://mothereff.in/utf-8#%C3%A9
