### ISSUE TITLE
fills screen with garbage, regardless of arguments passed

### ISSUE THREAD

**Issue by DougReeder** [skddc/rs-backup#19]
to reproduce
Under macOS 11.6.1, with node v14.16.1 installed:
1. install with `npm install -g rs-backup`
2. run with `rs-backup`

Expected outcome: console message: 'Please provide a backup directory path via the --backup-dir option'

Actual outcome: screen filled with garbage:
<img width="1170" alt="garbage from rs-backup" src="https://user-images.githubusercontent.com/378430/148776716-a9b669ae-a0ac-412d-b887-e0896fc22489.png">

**Comment by DougReeder** [comment]
Works fine when run directly: `node backup.js -o somedir`

**Comment by raucao** [comment]
That outcome is unexpected indeed!

I have just verified that it works as expected with node 14 and standard bash on Linux. Unfortunately, I have no way of debugging it on macOS at the moment. @DougReeder If you could help with it, that would be fantastic!

**Comment by raucao** [comment]
Could have something to do with https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/

**Comment by DougReeder** [comment]
That appears to be the root cause. `npm ci` doesn't work with the -g flag, so it's not clear how to install globally at the moment.  Presumably github and npm will stop serving the problematic versions.
