### ISSUE TITLE
Output could be silenced

### ISSUE THREAD

**Issue by rosano** [skddc/rs-backup#20]
I run this via node `exec` and it crashes with `RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded`, which I currently fix by setting its `maxBuffer` to `5 * 1024 * 1024`, but I suppose a `--silent` flag could be generally useful as well.

**Comment by raucao** [comment]
Interesting! Could you explain the use case a little bit, so I can understand how you're using the program there?

**Comment by rosano** [comment]
I'm running the command via a node server (although now I realize that might not be the best way) so that I can trigger a backup via HTTP request, then once it's done I move the files somewhere else.

**Comment by rosano** [comment]
> it crashes

Just to be clear it's `exec` and not `rs-backup` that crashes, as I understand.

**Comment by raucao** [comment]
I see, thanks.

If that's running on a server, I would generally recommend using a cron job or systemd timer for that.

However, to solve this specific issue, have you tried the [`stdio` option](https://nodejs.org/api/child_process.html#optionsstdio)?

**Comment by rosano** [comment]
> However, to solve this specific issue, have you tried the [`stdio` option](https://nodejs.org/api/child_process.html#optionsstdio)?

Ah cool, will do!
