### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by jorinvo** [skddc/rs-backup#3]
https://www.npmjs.com/search?q=rs-backup

**Comment by raucao** [comment]
I'm still waiting for at least one person to tell me that it worked for them before publishing it. ;)

**Comment by jorinvo** [comment]
@skddc I can't figure out which options to pass...
I was guessing something like this: `node backup.js -i https://storage.5apps.com/jorin/ -o test --token`.
But don't know where to get the token.

**Comment by raucao** [comment]
You'll need to acquire the token from an app or your server somehow. You can inspect localStorage for example. If you do that with the [browser example app](https://remotestorage-browser.5apps.com/) you'll have a root token that works for the whole storage.

**Comment by raucao** [comment]
... that's why #2 exists. ;)

**Comment by jorinvo** [comment]
Thanks, wasn't sure which token first. But when I open an app from the 5apps dashboard the access_token is right in the URL bar.

It seems to be backing up smoothly. Some error notices for files that do not exist anymore, but that  doesn't break it.

Even worked for some bigger files. A 13mb gif file takes like 10 min to download in Bangkok via VPN. But it worked!

I won't try the restoring with my account though :wink: 

Nice work!

**Comment by raucao** [comment]
Cool, thanks for testing!

You can restore to a different account, if you want to test, although it sounds like that might take a while on your connection. ;)

**Comment by raucao** [comment]
Published: https://www.npmjs.com/package/rs-backup

**Comment by jorinvo** [comment]
Awesome! Now `npm i -g rs-backup` also works!
